name: Update gradle version

on:
  workflow_dispatch:
    inputs:
      gradle-version:
        description: Gradle version
        default: latest
        type: string
        required: false

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: qupath/actions/.github/workflows/update-gradle.yml@main
        with:
          gradle-version: ${{ inputs.gradle-version }}
